{% set name = "langchain-openai" %}
{% set version = "0.3.16" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 4e423e39d072f1432adc9430f2905fe635cc019f01ad1bdffa5ed8d0dda32149

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - pdm-backend
  run:
    - python
    - langchain-core >=0.3.58,<1
    - openai >=1.68.2,<2.0.0
    - tiktoken >=0.7,<1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - raybellwaves
