{% set name = "langchain-openai" %}
{% set version = "0.3.16" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 4e423e39d072f1432adc9430f2905fe635cc019f01ad1bdffa5ed8d0dda32149

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - pdm-backend
  run:
    - python
    - langchain-core >=0.3.58,<1
    - openai >=1.68.2,<2.0.0
    - tiktoken >=0.7,<1

test:
  source_files:
    - tests
  requires:
    # Commented dependencies are ones that are specified by upstream but missing on our channels
    - pip
    - pytest >=7.3.0,<8
    - freezegun >=1.2.2,<2
    - pytest-mock >=3.10.0,<4
    # - syrupy >=4.0.2,<5
    # - pytest-watcher >=0.3.4,<1
    - pytest-asyncio >=0.21.1,<1
    - pytest-cov >=4.1.0,<5
    # - pytest-retry >=1.7.0,<1.8.0
    - pytest-socket >=0.6.0,<1
    - pytest-xdist >=3.6.1,<4
    - numpy >=1.26.4  # [py<313]
    - numpy >=2.1.0  # [py>=313]
    # - langchain-tests
  commands:
    - pip check
    {% set pytest_flags = "" %}
    # Missing: langchain-tests
    {% set pytest_flags = pytest_flags + " --ignore=tests/unit_tests/chat_models" %}
    {% set pytest_flags = pytest_flags + " --ignore=tests/unit_tests/embeddings/test_base_standard.py" %}
    {% set pytest_flags = pytest_flags + " --ignore=tests/unit_tests/embeddings/test_azure_standard.py" %}
    - pytest -vv tests/unit_tests {{ pytest_flags }}
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  doc_url: https://python.langchain.com/docs/integrations/providers/openai/
  summary: LangChain integrations for OpenAI through their openai SDK
  description: This package contains the LangChain integrations for OpenAI through their openai SDK.

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - raybellwaves
