{% set version = "0.1.20" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 2c91e9f771541076b138e65dd4c5427b26957a2272406a7f4ee747d7896f9b35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - langchain-core >=0.2.24,<0.3
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - pavelzw
    - raybellwaves
